CREATE TABLE Other(
	ID INT NOT NULL AUTO_INCREMENT,
    ArtObjectID INT NOT NULL REFERENCES ArtObject(ID),
    MaterialType VARCHAR(30) NOT NULL,
    Style VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID)
);