/*************************************************************
 *      file: HangmanResultFrame.java
 *      author: Michael Muinos
 *      class: CS 245 - Programming Graphical User Interfaces
 *  
 *      assignment: Quarter Project, Checkpoint # 1
 *      date last modified: 8/8/16
 * 
 *      purpose: The purpose of this class is to create a new JFrame
 *      object that displays to the user the result of the hangman
 *      game (whether they won, lost, or skipped).
 ************************************************************/
package cs245project;


import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

public class ResultFrame extends javax.swing.JFrame {
    
    private int totalScore;
    private boolean isHighScore;

    // constructor: HangmanresultFrame
    // purpose: the following constructor will create a new JFrame object.
    // Additionally, it passes in the result text and users score
    // from the hangman game and updates the labels.
    public ResultFrame(int totalScore) {
        initComponents();
        this.totalScore = totalScore;
        
        alertMessage.setVisible(false);
        scoreLabel.setText("Total Score: " + String.valueOf(totalScore));
        
        isHighScore = isHighScore();
        
        if(!isHighScore) {
            nameTextField.setVisible(false);
            titleLabel.setVisible(false);
        }
    }
    
    // method:setResultFrameAttributes
    // purpose: This method will force the Jframe to be displayed
    // in the center of the screen and make it seen.
    public void setResultFrameAttributes() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        EscapeAction escape = new EscapeAction();
        escape.register(getRootPane());
        F1Action dialog = new F1Action();
        dialog.register(getRootPane());
    }
    
    // method: isHighScore
    // purpose: Determines if the user has a highscore or not (top 5)
    private boolean isHighScore() {
        if(!new File(HighScoreDeserializer.FILE_NAME).exists()) {
            return true;
        }
        
        ArrayList<HighScore> list = HighScoreDeserializer.deserializeHighScoreList();
        if(list.size() < 5) {
            return true;
        }

        for(int i = 0; i < list.size(); i++) {
            if(list.get(i).getScore() < totalScore) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hangmanLabel = new javax.swing.JLabel();
        endButton = new javax.swing.JButton();
        scoreLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        alertMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hangmanLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/HangmanLogo1.png"))); // NOI18N
        hangmanLabel.setText("Hangman");
        hangmanLabel.setPreferredSize(new java.awt.Dimension(150, 62));

        endButton.setText("End");
        endButton.setToolTipText("Gave Over! This button takes you to main page.");
        endButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endButtonActionPerformed(evt);
            }
        });
        add(endButton);

        scoreLabel.setText("jLabel1");

        titleLabel.setText("Enter three letter name:");

        alertMessage.setText("ENTER 3 LETTER NAME ABOVE!");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/PoképickLogo.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SudokuLogo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hangmanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(alertMessage)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(endButton)
                                    .addGap(72, 72, 72))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(titleLabel)
                                    .addGap(31, 31, 31)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(scoreLabel))
                            .addComponent(jLabel2))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(hangmanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addComponent(scoreLabel)
                .addGap(18, 18, 18)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(alertMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endButton)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // method: mainMenuButtonActionPerformed
    // purpose: this method was auto-generated by NetBeans. It will create a new
    // main menu jframe and dispose of the current frame.
    private void endButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endButtonActionPerformed
        if(isHighScore) {
            if(!nameTextField.getText().trim().isEmpty() && nameTextField.getText().trim().length() == 3) {
                HighScoreSerializer serialize = new HighScoreSerializer(new HighScore(nameTextField.getText().trim().toUpperCase(), totalScore));
                serialize.serializeHighScore();
                
                MainMenuFrame mainMenu = new MainMenuFrame();
                mainMenu.setMainMenuAttributes();
                this.dispose();
            } else {
                Border border = BorderFactory.createLineBorder(Color.RED);
                nameTextField.setBorder(border);
                alertMessage.setVisible(true);
            }
        } else {
            MainMenuFrame mainMenu = new MainMenuFrame();
            mainMenu.setMainMenuAttributes();
            this.dispose();
        }
    }//GEN-LAST:event_endButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertMessage;
    private javax.swing.JButton endButton;
    private javax.swing.JLabel hangmanLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
